# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    setup_ci if ENV['CI']
    app_store_connect_api_key(
      key_id: ENV['APPSTORE_API_KEY_ID'],
      issuer_id: ENV['APPSTORE_ISSUER_ID'],
      key_content: ENV['APPSTORE_API_PRIVATE_KEY']
    )
    match(type: 'appstore')
    increment_version_number_in_xcodeproj(
      bump_type: 'minor'
    )
    increment_build_number
    build_app(workspace: "App.xcworkspace", scheme: "App")
    sentry_debug_files_upload
    clean_build_artifacts
    new_version = get_version_number_from_xcodeproj
    commit_version_bump(
      message: "chore: bump version to #{new_version}",
      xcodeproj: "App.xcodeproj",
      force: true
    )
    upload_to_app_store(
      force: true,
      precheck_include_in_app_purchases: false
    )
    push_to_git_remote
  end
end
