name: Ship iOS App

on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: "Version bump type"
        required: true
        default: "minor"
        type: choice
        options:
          - minor
          - patch
          - major
jobs:
  build:
    runs-on: macOS-latest
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Pull .env from Vercel
        run: npx vercel env pull .env --token ${{ secrets.VERCEL_TOKEN }} --environment production --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Create temporary .npmrc and install dependencies
        run: |
          node --env-file=.env utils/generate-npmrc.js
          npm install --no-audit --no-fund
          rm -f .npmrc
        env:
          SKIP_POSTINSTALL: true
      - name: Build Capacitor app
        run: |
          set -a
          source .env
          set +a
          npm run build:static:prod
      - uses: matbour/setup-sentry-cli@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./out"
      - name: Install dependencies
        run: bundle install
        working-directory: ./ios/App/fastlane
      - run: bundle exec fastlane ios release
        working-directory: ./ios/App/fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APPSTORE_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
          APPSTORE_API_KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
          APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG_SLUG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT_SLUG: ${{ secrets.SENTRY_PROJECT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_BUMP_TYPE: ${{ inputs.version_bump_type }}
