name: Ship iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Pull .env from Vercel
        run: npx vercel env pull .env --token ${{ secrets.VERCEL_TOKEN }} --environment production --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Create temporary .npmrc and install dependencies
        run: |
          node --env-file=.env utils/generate-npmrc.js
          npm install --no-audit --no-fund
          rm -f .npmrc
        env:
          SKIP_POSTINSTALL: true
      - name: Build Capacitor app
        run: |
          set -a
          source .env
          set +a
          npm run build:static:prod
      - uses: matbour/setup-sentry-cli@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./out"
      - uses: Apple-Actions/import-codesign-certs@v3
        id: download-profiles
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - name: Install certificate
        run: |
          echo "${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}" | base64 --decode > ./cert.p12
          security create-keychain -p "" build.keychain
          security import ./cert.p12 -k build.keychain -P "${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}" -A
          security list-keychains -d user -s build.keychain
          security default-keychain -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.APPSTORE_PROVISIONING_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
      - name: Build archive
        run: ./ios/Build
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          DEVELOPMENT_TEAM: ${{ vars.APPSTORE_TEAM_ID }}
      - name: Upload debug files to Sentry
        run: sentry-cli debug-files upload --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} --org ${{ secrets.SENTRY_ORG }} --project ${{ secrets.SENTRY_PROJECT }} .build/Archives/App.xcarchive/dSYMs/App.app.dSYM
      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: "./ios/build/App.ipa"
          issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ vars.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
