name: Ship iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Pull .env from Vercel
        run: npx vercel env pull .env --token ${{ secrets.VERCEL_TOKEN }} --environment production --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Create temporary .npmrc and install dependencies
        run: |
          npm install -D dotenv
          node utils/generate-npmrc.js
          npm ci --no-audit --no-fund
          rm -f .npmrc
      - name: Build Capacitor app
        run: |
          set -a
          source .env
          set +a
          npm run build:static:prod
      - uses: matbour/setup-sentry-cli@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./out"
      - uses: Apple-Actions/import-codesign-certs@v3
        id: download-profiles
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - uses: Apple-Actions/download-provisioning-profiles@v4
        with:
          bundle-id: ${{ vars.APPSTORE_BUNDLE_ID }}
          profile-type: "IOS_APP_STORE"
          issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ vars.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      - name: Debug provisioning profiles
        run: |
          echo '${{ steps.download-profiles.outputs.profiles }}' | jq .
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Set provisioning profile name env var
        run: |
          PROFILE_NAME=$(echo '${{ steps.download-profiles.outputs.profiles }}' | jq -r '.[0].name')
          echo "PROVISIONING_PROFILE_NAME=$PROFILE_NAME" >> $GITHUB_ENV
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
      - name: Build archive
        run: ./ios/Build
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          DEVELOPMENT_TEAM: ${{ vars.APPSTORE_TEAM_ID }}
      - name: Upload debug files to Sentry
        run: sentry-cli debug-files upload --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} --org ${{ secrets.SENTRY_ORG }} --project ${{ secrets.SENTRY_PROJECT }} .build/Archives/App.xcarchive/dSYMs/App.app.dSYM
      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v3
        with:
          app-path: "./ios/build/App.ipa"
          issuer-id: ${{ vars.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ vars.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
